### ISSUE TITLE
Incorrect Normalized Power, TSS, and Intensity calculated for a ride.

### ISSUE THREAD

**Issue by jrwagz** [mayfield/strava-sauce#2]
First of all, thank you for this plugin, it's super awesome!  I use it daily and it's super useful.

Here is a ride that for some reason is getting it's Normalized Power, and thus Intensity, and TSS calculated incorrectly.  https://www.strava.com/activities/492879155

The "correct" Normalized Power is 285, however Strava Sauce is calulating it as 260.  This is the first time I've ever seen it get calculated incorrectly, and I've used it daily for a couple months now.

Here is a spreadsheet with the raw data for this ride, and you can see where I calculate the Normalized Power (with the formula from Training and Racing with a Power Meter) and get 285.
[newman_hauser.xlsx](https://github.com/mayfield/strava-sauce/files/129505/newman_hauser.xlsx)

Also, here is the .gpx file exported from Strava (in a zip, since GitHub doesn't like .gpx), in case it helps you diagnose the problem better.
[Newman and Hauser loop w- Craig, Luther, Jay and Edwin.zip](https://github.com/mayfield/strava-sauce/files/129509/Newman.and.Hauser.loop.w-.Craig.Luther.Jay.and.Edwin.zip)

**Comment by mayfield** [comment]
Hi Justin,

My guess is that Strava did some tweaks to the power data that are leading to discrepancies.  The GPX export from strava (and the source file) don't always line up with the data available inside the strava site (which sauce ultimately feeds from).  Some of this can be related to Strava doing its own "Moving time" calculations that may produce zero watt records that were not recorded by your head unit.  The fact that Sauce and Strava's NP calcs are within 5 watts (and sauce is the higher of the two) makes me think the problem lies in how strava is massaging the data stream.  That being said, I'm curious and want to validate any of this conclusively.  So I'll take a close look as soon as I have some free time.  Thanks for using Sauce and I'm glad you find it useful!

PS: The NP formula borrows heavily from the technique used in Golden Cheetah which is pretty simple.  There is basically no interpolation taking place.

**Comment by jrwagz** [comment]
Thanks @mayfield , I think you are right that Strava is doing some strange massaging of the data.  I took a look at your method that calculates NP (https://github.com/mayfield/strava-sauce/blob/master/src/lib.js#L245) and it looks spot on.  Do you have an easy way of extracting the power values that Strava is providing to your plugin?  If we get a hold of that then we could compare it to the raw watt-stream that I exported from GoldenCheetah (that's how I came up with the Excel spreadsheet I attached).

**Comment by mayfield** [comment]
Hi @jrwagz,

[watt_stream.txt](https://github.com/mayfield/strava-sauce/files/129570/watt_stream.txt)

Incidentally, I tried loading the gpx file you attached in GC and it didn't show me watt data.  However I haven't used GC in ages, so it might be my setup.

**Comment by mayfield** [comment]
Just from a quick eyeballing, your spreadsheet data looks drastically different from the stream in Strava.  So I'm guessing this is out of my hands.   One theory is that GPS data may have been suspect leading to bouts of what appeared to be non-moving data.  So Strava may have been discrediting certain sections and then zero-padding others to compensate.  Regardless, I don't know that there is much or anything I can do from the context of a chrome ext.  I'm happy to be proven wrong though, so let me know if you have any insights to handle this better.

**Comment by jrwagz** [comment]
@mayfield , I think you are right, this looks like Strava is doing something to the watt data, and that might be because of some GPS inaccuracies.  I'm going to investigate further to see if I can validate that fact, however at this point I don't believe there is anything wrong with the plugin, so I'll mark the issue as closed.

I will however still update this with my findings as I think you may be interested in seeing them.

It doesn't surprise me that the .tcx file didn't have watt data, I think I remember having that issue before.  Here is a .fit file that should be complete.
[Cyclemeter-Cycle-20160213-1140.zip](https://github.com/mayfield/strava-sauce/files/129917/Cyclemeter-Cycle-20160213-1140.zip)

I should note that this ride was recorded with an iPhone6 using the Cyclemeter application.

**Comment by jrwagz** [comment]
Here is why I think there may be something to your theory about there being GPS glitches.  When I import the ride to Golden Cheetah and view it's map view, I see this:

![image](https://cloud.githubusercontent.com/assets/498172/13036562/6470c400-d31f-11e5-9fdd-2daf6ca962c8.png)

![image](https://cloud.githubusercontent.com/assets/498172/13036559/5fa20a06-d31f-11e5-9fdb-d9cf95778518.png)

**Comment by jrwagz** [comment]
Bingo, looks like the GPS data must have lost it's mind periodically:

![image](https://cloud.githubusercontent.com/assets/498172/13036588/2e87e976-d320-11e5-9563-23ba810c563d.png)

**Comment by jrwagz** [comment]
It looks like this is possibly an artifact of the "stop detection" feature of Cyclemeter, if I learn anything more I'll post it here.

I also did an experiment where I disabled "stop detection", re-exported the ride from Cyclemeter (since stop detection is only applied on export) and uploaded to a Strava account, however the normalized power still showed about 20-25w low on Strava and Strava Sauce as compared to Training Peaks, and Cyclemeter.  However I notice that Golden Cheetah seems to be closer the calculation shown in Strava Sauce, but it is still 3w different.
[Cyclemeter-Cycle-20160213-1140_no_stop_detection.zip](https://github.com/mayfield/strava-sauce/files/129949/Cyclemeter-Cycle-20160213-1140_no_stop_detection.zip)

**Comment by mayfield** [comment]
Very interesting findings Justin.  Just to be sure, TP and Cyclemeter are not set to ignore zeros I assume?

**Comment by jrwagz** [comment]
I don't recall seeing any setting about that, however I think that ignoring zero power values would likely increase the 30s average power numbers, and therefore cause NP to be higher, although it would also reduce the overall workout time, which might offset the overall affect to TSS.  Also, "the book" doesn't say anything about ignoring zeroes, so any software that does, would be straying from the standard in my opinion.

**Comment by mayfield** [comment]
Looking back into these calcs and finding some bugs with respect to CP calcs with irregular sample rates and also when there are data gaps (periods large enough that we need to zero pad to avoid false high readings).  Working on a safer more accurate algo now.

**Comment by mayfield** [comment]
I think I've fixed some of the bugs related to this issue.

Should be addressed in the next release.
