### ISSUE TITLE
NP only shows on full activity and not when only a portion is selected

### ISSUE THREAD

**Issue by tomglynch** [mayfield/strava-sauce#5]
In a ride analysis, the normalised power for the whole ride is shown as such: 
![image](https://user-images.githubusercontent.com/17879963/68456454-e7a24780-0251-11ea-9714-ee29b3964a8d.png)

However, if you select only a portion of the ride the np value disappears. 

This could potentially be quite a quick fix, so I'm submitting an issue. If it's rather complex I am happy to take a look at your code and see if I can implement. 

It's a ripper extension, thanks so much,

Tom

**Comment by mayfield** [comment]
Hey Tom,

NP should work for any durations over 20 minutes.  Andy Coggan doesn't recommend NP for anything less than about 20 minutes so the calcs only work with 1000 data points.  Are you not seeing it display for long selections too?

Here's the snippet of code...
![image](https://user-images.githubusercontent.com/139316/68496509-c456a880-020f-11ea-84c5-63ce5c5e8c1b.png)

**Comment by tomglynch** [comment]
Good call, I am seeing it for longer selections after giving it a go. Thanks for the info and sorry I didn't reply earlier, just forgot to reply. Cheers :)
